"""Added job_listings relationship to Employer

Revision ID: c9095cd09bb5
Revises: 668373f6dce6
Create Date: 2025-03-12 17:58:51.666437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9095cd09bb5'
down_revision: Union[str, None] = '668373f6dce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('job_listings', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('job_listings', 'qualifications',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('job_listings', 'salary_range',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('job_listings', 'benefits',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('job_listings', 'deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('job_listings', 'benefits',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('job_listings', 'salary_range',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_listings', 'qualifications',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('job_listings', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('job_listings', 'created_at')
    # ### end Alembic commands ###
